[package]
name = "dotbackup"
version = "0.1.0"
edition = "2021"
description = "Dotfile backup utility"
homepage = "https://github.com/jaxvanyang/dotbackup.rs"
license-file = "LICENSE"
default-run = "dotbackup"

[dependencies]
dirs = "6.0.0"
expanduser = "1.2.2"
glob = "0.3.2"
saphyr = "0.0.3"
